version: "3"
services:
  api:
    build:
      context: api/
    ports:
      - "5001:5001"
    expose:
      - "5001"
    volumes:
      - ./api/:/app
  gui:
    build:
      context: gui/
    ports:
      - "4200:4200"
    expose:
      - "4200"
