FROM python:3.7.13-alpine

COPY requirements.txt /
RUN pip3 install -r /requirements.txt

COPY . /app
WORKDIR /app

ENTRYPOINT ["gunicorn", "flask-app:app", "--workers=4", "-b", "0.0.0.0:5000"]